version: '3'

networks:
  app_tier:
    driver: bridge

services:
  prisma_postgres:
    container_name: scrum_poker_postgres
    image: bitnami/postgresql
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - prisma_postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    networks:
      - app_tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: scrum_poker_api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:3000
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@scrum_poker_postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    command: ash -c "npx prisma migrate dev && pnpm i && pnpm start:dev"
    networks:
      - app_tier
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      prisma_postgres:
        condition: service_healthy

  prisma_studio:
    container_name: scrum_poker_studio
    image: timothyjmiller/prisma-studio
    restart: on-failure
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@scrum_poker_postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    networks:
      - app_tier
    depends_on:
      prisma_postgres:
        condition: service_healthy
      app:
        condition: service_healthy

volumes:
  prisma_postgres: